using System;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using ReactiveUI; // Keep for MessageBus
using KaraokePlayer.Models;
using KaraokePlayer.Services;
using LibVLCSharp.Shared;
using Avalonia.Media.Imaging;

namespace KaraokePlayer.ViewModels;

public partial class PlaybackWindowViewModel : ViewModelBase
{
    private readonly IMediaPlayerController? _mediaPlayerController;
    private readonly IAudioVisualizationEngine? _audioVisualizationEngine;
    
    [ObservableProperty]
    private MediaFile? _currentSong;
    
    [ObservableProperty]
    private bool _isPlaying;
    
    [ObservableProperty]
    private double _currentTime;
    
    [ObservableProperty]
    private double _duration;
    
    [ObservableProperty]
    private bool _subtitlesEnabled = true;
    
    [ObservableProperty]
    private bool _subtitlesVisible;
    
    [ObservableProperty]
    private string _currentSubtitle = string.Empty;
    
    [ObservableProperty]
    private bool _isFullscreen;
    
    [ObservableProperty]
    private bool _isBuffering;
    
    [ObservableProperty]
    private bool _hasMedia;
    
    [ObservableProperty]
    private bool _isVideoContent;
    
    [ObservableProperty]
    private bool _isAudioContent;
    
    [ObservableProperty]
    private string _currentTitle = string.Empty;
    
    [ObservableProperty]
    private string _currentArtist = string.Empty;
    
    [ObservableProperty]
    private Bitmap? _currentArtwork;
    
    [ObservableProperty]
    private string _visualizationStyle = "bars";

    // Design-time constructor
    public PlaybackWindowViewModel()
    {
        InitializeCommands();
        LoadSampleData();
    }

    // Runtime constructor with dependency injection
    public PlaybackWindowViewModel(
        IMediaPlayerController mediaPlayerController,
        IAudioVisualizationEngine? audioVisualizationEngine = null)
    {
        _mediaPlayerController = mediaPlayerController ?? throw new ArgumentNullException(nameof(mediaPlayerController));
        _audioVisualizationEngine = audioVisualizationEngine;

        InitializeCommands();
        SubscribeToServiceEvents();
    }

    private void InitializeCommands()
    {
        // Commands are now auto-generated via RelayCommand attributes
    }

    private void SubscribeToServiceEvents()
    {
        // Subscribe to MediaPlayerController events directly
        if (_mediaPlayerController != null)
        {
            _mediaPlayerController.StateChanged += OnPlaybackStateChanged;
            _mediaPlayerController.TimeChanged += OnPlaybackTimeChanged;
            _mediaPlayerController.MediaEnded += OnMediaEnded;
            _mediaPlayerController.PlaybackError += OnPlaybackError;
        }

        // Subscribe to message bus for cross-window state synchronization
        SubscribeToMessageBus();
    }

    private void SubscribeToMessageBus()
    {
        // Listen for playback state updates from other windows
        ReactiveUI.MessageBus.Current.Listen<PlaybackStateMessage>()
            .Subscribe(msg =>
            {
                CurrentSong = msg.CurrentSong;
                IsPlaying = msg.IsPlaying;
                CurrentTime = msg.CurrentTime;
                Duration = msg.Duration;
            });

        // Listen for media change messages
        ReactiveUI.MessageBus.Current.Listen<MediaChangedMessage>()
            .Subscribe(msg =>
            {
                CurrentSong = msg.MediaFile;
            });

        // Listen for subtitle toggle messages
        ReactiveUI.MessageBus.Current.Listen<SubtitleToggleMessage>()
            .Subscribe(msg =>
            {
                SubtitlesEnabled = msg.Enabled;
            });
    }

    // OnChanged partial methods for properties that need to trigger additional logic
    partial void OnCurrentSongChanged(MediaFile? value)
    {
        UpdateMediaInfo();
    }

    partial void OnSubtitlesEnabledChanged(bool value)
    {
        UpdateSubtitlesVisibility();
    }

    public MediaPlayer? MediaPlayer => _mediaPlayerController?.GetActiveMediaPlayer();

    // Commands (auto-generated by RelayCommand attributes)

    // Events
    public event EventHandler<bool>? FullscreenRequested;
    public event EventHandler? VisualizationUpdateRequested;

    // Command implementations
    [RelayCommand]
    private void ToggleFullscreen()
    {
        IsFullscreen = !IsFullscreen;
        FullscreenRequested?.Invoke(this, IsFullscreen);
    }

    [RelayCommand]
    private void ToggleSubtitles()
    {
        SubtitlesEnabled = !SubtitlesEnabled;
        _mediaPlayerController?.ToggleSubtitles(SubtitlesEnabled);

        // Broadcast subtitle toggle via message bus
        ReactiveUI.MessageBus.Current.SendMessage(new SubtitleToggleMessage
        {
            Enabled = SubtitlesEnabled
        });
    }

    // Service event handlers
    private void OnPlaybackStateChanged(object? sender, PlaybackStateChangedEventArgs e)
    {
        IsPlaying = e.NewState == PlaybackState.Playing;
        IsBuffering = e.NewState == PlaybackState.Buffering;
        
        if (e.NewState == PlaybackState.Playing)
        {
            HasMedia = true;
        }
        else if (e.NewState == PlaybackState.Stopped)
        {
            HasMedia = false;
        }

        // Broadcast state change via message bus for cross-window synchronization
        BroadcastPlaybackState();
    }

    private void OnPlaybackTimeChanged(object? sender, TimeChangedEventArgs e)
    {
        CurrentTime = e.CurrentTime;
        Duration = e.Duration;

        // Request visualization update for audio content
        if (IsAudioContent)
        {
            VisualizationUpdateRequested?.Invoke(this, EventArgs.Empty);
        }

        // Broadcast time update via message bus (throttled to avoid excessive messages)
        BroadcastPlaybackState();
    }

    private void OnMediaEnded(object? sender, MediaEndedEventArgs e)
    {
        HasMedia = false;
        CurrentSong = null;

        // Broadcast state change via message bus
        BroadcastPlaybackState();
    }

    private void OnPlaybackError(object? sender, PlaybackErrorEventArgs e)
    {
        // Error handling - could show error message in UI
        HasMedia = false;

        // Broadcast state change via message bus
        BroadcastPlaybackState();
    }

    /// <summary>
    /// Broadcasts current playback state to other windows via message bus
    /// </summary>
    private void BroadcastPlaybackState()
    {
        ReactiveUI.MessageBus.Current.SendMessage(new PlaybackStateMessage
        {
            CurrentSong = CurrentSong,
            IsPlaying = IsPlaying,
            CurrentTime = CurrentTime,
            Duration = Duration
        });
    }

    // Helper methods
    private void UpdateMediaInfo()
    {
        if (CurrentSong != null)
        {
            HasMedia = true;
            IsVideoContent = CurrentSong.Type == Models.MediaType.Video;
            IsAudioContent = CurrentSong.Type == Models.MediaType.Audio;

            CurrentTitle = CurrentSong.Metadata?.Title ?? CurrentSong.Filename;
            CurrentArtist = CurrentSong.Metadata?.Artist ?? string.Empty;

            // Load artwork for audio files
            if (IsAudioContent && !string.IsNullOrEmpty(CurrentSong.ThumbnailPath))
            {
                try
                {
                    CurrentArtwork = new Bitmap(CurrentSong.ThumbnailPath);
                }
                catch
                {
                    CurrentArtwork = null;
                }
            }
            else
            {
                CurrentArtwork = null;
            }

            UpdateSubtitlesVisibility();
        }
        else
        {
            HasMedia = false;
            IsVideoContent = false;
            IsAudioContent = false;
            CurrentTitle = string.Empty;
            CurrentArtist = string.Empty;
            CurrentArtwork = null;
            SubtitlesVisible = false;
        }
    }

    private void UpdateSubtitlesVisibility()
    {
        // Show subtitles only for video content when enabled
        SubtitlesVisible = IsVideoContent && SubtitlesEnabled && HasMedia;
    }

    public float[] GetAudioSpectrum()
    {
        // Get audio spectrum from media player controller
        return _mediaPlayerController?.GetAudioSpectrum() ?? Array.Empty<float>();
    }

    // Message bus methods for cross-window communication
    public void SendPlayPauseCommand()
    {
        // Send play/pause command via message bus
        ReactiveUI.MessageBus.Current.SendMessage(new PlaybackControlMessage { Action = "PlayPause" });
    }

    public void SendNextCommand()
    {
        ReactiveUI.MessageBus.Current.SendMessage(new PlaybackControlMessage { Action = "Next" });
    }

    public void SendPreviousCommand()
    {
        ReactiveUI.MessageBus.Current.SendMessage(new PlaybackControlMessage { Action = "Previous" });
    }

    public void SendVolumeUpCommand()
    {
        ReactiveUI.MessageBus.Current.SendMessage(new PlaybackControlMessage { Action = "VolumeUp" });
    }

    public void SendVolumeDownCommand()
    {
        ReactiveUI.MessageBus.Current.SendMessage(new PlaybackControlMessage { Action = "VolumeDown" });
    }

    public void SendMuteCommand()
    {
        ReactiveUI.MessageBus.Current.SendMessage(new PlaybackControlMessage { Action = "Mute" });
    }

    private void LoadSampleData()
    {
        // Sample data for design-time preview
        CurrentTitle = "Sample Song Title";
        CurrentArtist = "Sample Artist";
        HasMedia = true;
        IsAudioContent = true;
        Duration = 245;
        CurrentTime = 60;
    }

    /// <summary>
    /// Cleanup method to unsubscribe from events when the ViewModel is disposed
    /// </summary>
    public void Cleanup()
    {
        if (_mediaPlayerController != null)
        {
            _mediaPlayerController.StateChanged -= OnPlaybackStateChanged;
            _mediaPlayerController.TimeChanged -= OnPlaybackTimeChanged;
            _mediaPlayerController.MediaEnded -= OnMediaEnded;
            _mediaPlayerController.PlaybackError -= OnPlaybackError;
        }
    }
}

// Message classes for cross-window communication

/// <summary>
/// Message for playback control commands (play, pause, next, etc.)
/// </summary>
public class PlaybackControlMessage
{
    public string Action { get; set; } = string.Empty;
}

/// <summary>
/// Message for playback state synchronization across windows
/// </summary>
public class PlaybackStateMessage
{
    public MediaFile? CurrentSong { get; set; }
    public bool IsPlaying { get; set; }
    public double CurrentTime { get; set; }
    public double Duration { get; set; }
}

/// <summary>
/// Message for media change notifications
/// </summary>
public class MediaChangedMessage
{
    public MediaFile? MediaFile { get; set; }
}

/// <summary>
/// Message for subtitle toggle notifications
/// </summary>
public class SubtitleToggleMessage
{
    public bool Enabled { get; set; }
}
