// <auto-generated />
using System;
using KaraokePlayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaraokePlayer.Models.Migrations
{
    [DbContext(typeof(KaraokeDbContext))]
    partial class KaraokeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("KaraokePlayer.Models.AppSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AudioBoostEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioOutputDevice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoPlayEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CacheSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CrossfadeDuration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CrossfadeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FontSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PreloadBufferSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShuffleMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisualizationStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("KaraokePlayer.Models.MediaFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MetadataLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ThumbnailLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("Filename");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("KaraokePlayer.Models.MediaMetadata", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasSubtitles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolutionHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResolutionWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Artist");

                    b.HasIndex("MediaFileId")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("MediaMetadata");
                });

            modelBuilder.Entity("KaraokePlayer.Models.PlaylistItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("Position");

                    b.ToTable("PlaylistItems");
                });

            modelBuilder.Entity("KaraokePlayer.Models.MediaMetadata", b =>
                {
                    b.HasOne("KaraokePlayer.Models.MediaFile", "MediaFile")
                        .WithOne("Metadata")
                        .HasForeignKey("KaraokePlayer.Models.MediaMetadata", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("KaraokePlayer.Models.PlaylistItem", b =>
                {
                    b.HasOne("KaraokePlayer.Models.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("KaraokePlayer.Models.MediaFile", b =>
                {
                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
